import 'package:flutter/material.dart';

enum PatternGroup { reversal, continuation, triangles, candles, context }
enum PatternShape { doubleTop, doubleBottom, tripleTop, tripleBottom, headShoulders, inverseHeadShoulders, roundingTop, roundingBottom, flag, pennant, ascendingTriangle, descendingTriangle, symmetricalTriangle, rectangle, cupHandle, inverseCupHandle, wedge, channel, broadening, pinBar, engulfing, doji, star }

class PatternInfo {
  final String name, english, classification, direction, description, structure, confirmation, notes;
  final PatternGroup group; final PatternShape shape;
  const PatternInfo({required this.name,required this.english,required this.group,required this.shape,required this.classification,required this.direction,required this.description,required this.structure,required this.confirmation,required this.notes});
}

const patternLibrary=<PatternInfo>[
  PatternInfo(name:'القمة المزدوجة',english:'Double Top',group:PatternGroup.reversal,shape:PatternShape.doubleTop,classification:'انعكاسي',direction:'هابط',description:'قمتان متقاربتان بعد سياق صاعد وبينهما قاع فاصل.',structure:'قمتان + قاع فاصل',confirmation:'كسر القاع الفاصل ثم تأكيد الحركة.',notes:'الشكل وحده لا يكفي؛ السياق مهم.'),
  PatternInfo(name:'القاع المزدوج',english:'Double Bottom',group:PatternGroup.reversal,shape:PatternShape.doubleBottom,classification:'انعكاسي',direction:'صاعد',description:'قاعان متقاربان بعد سياق هابط وبينهما قمة فاصلة.',structure:'قاعان + قمة فاصل',confirmation:'كسر القمة الفاصلة ثم تأكيد الحركة.',notes:'راقب المنطقة والسياق قبل اعتبار النموذج مكتملاً.'),
  PatternInfo(name:'القمة الثلاثية',english:'Triple Top',group:PatternGroup.reversal,shape:PatternShape.tripleTop,classification:'انعكاسي',direction:'هابط',description:'ثلاث محاولات متقاربة لاختراق مقاومة بعد اتجاه صاعد.',structure:'3 قمم + دعم فاصل',confirmation:'كسر منطقة الدعم بين القمم.',notes:'تعامل مع المستويات كمناطق وليس خطوطاً دقيقة دائماً.'),
  PatternInfo(name:'القاع الثلاثي',english:'Triple Bottom',group:PatternGroup.reversal,shape:PatternShape.tripleBottom,classification:'انعكاسي',direction:'صاعد',description:'ثلاث محاولات متقاربة للدفاع عن دعم بعد اتجاه هابط.',structure:'3 قيعان + مقاومة فاصل',confirmation:'كسر المقاومة الفاصلة مع تأكيد.',notes:'راقب قوة الارتداد والسياق السابق.'),
  PatternInfo(name:'الرأس والكتفين',english:'Head & Shoulders',group:PatternGroup.reversal,shape:PatternShape.headShoulders,classification:'انعكاسي',direction:'هابط',description:'كتف أيسر ورأس أعلى وكتف أيمن مع خط عنق.',structure:'كتف + رأس + كتف + خط عنق',confirmation:'كسر خط العنق ثم التأكيد أو إعادة الاختبار.',notes:'الفروق البسيطة في الحجم لا تلغي الشكل.'),
  PatternInfo(name:'الرأس والكتفين المعكوس',english:'Inverse Head & Shoulders',group:PatternGroup.reversal,shape:PatternShape.inverseHeadShoulders,classification:'انعكاسي',direction:'صاعد',description:'كتف أيسر ورأس أعمق وكتف أيمن مع خط عنق علوي.',structure:'كتف + رأس + كتف + خط عنق',confirmation:'اختراق خط العنق ثم مراقبة التأكيد.',notes:'ضع النموذج داخل سياقه ولا تعزل الشكل.'),
  PatternInfo(name:'القمة المستديرة',english:'Rounding Top',group:PatternGroup.reversal,shape:PatternShape.roundingTop,classification:'انعكاسي',direction:'هابط',description:'تحول تدريجي من صعود إلى توازن ثم هبوط.',structure:'قوس علوي + دعم',confirmation:'فقدان الدعم أو البنية الصاعدة.',notes:'يحتاج وقتاً نسبياً ولا يثبت من حركات قصيرة.'),
  PatternInfo(name:'القاع المستدير',english:'Rounding Bottom',group:PatternGroup.reversal,shape:PatternShape.roundingBottom,classification:'انعكاسي',direction:'صاعد',description:'تحول تدريجي من هبوط إلى توازن ثم صعود.',structure:'قوس سفلي + مقاومة',confirmation:'اختراق المقاومة أو البنية الفاصلة.',notes:'راقب السياق وقوة الخروج.'),
  PatternInfo(name:'العلم الصاعد',english:'Bull Flag',group:PatternGroup.continuation,shape:PatternShape.flag,classification:'استمراري',direction:'صاعد',description:'اندفاع صاعد قوي ثم تصحيح قصير داخل قناة مائلة للأسفل.',structure:'سارية + قناة تصحيحية',confirmation:'الخروج من القناة باتجاه الحركة الأصلية.',notes:'ليست كل قناة هابطة علماً.'),
  PatternInfo(name:'العلم الهابط',english:'Bear Flag',group:PatternGroup.continuation,shape:PatternShape.flag,classification:'استمراري',direction:'هابط',description:'اندفاع هابط قوي ثم تصحيح قصير داخل قناة مائلة للأعلى.',structure:'سارية + قناة تصحيحية',confirmation:'كسر القناة باتجاه الهبوط.',notes:'السياق السابق يعطي الشكل معنى.'),
  PatternInfo(name:'الراية الصاعدة',english:'Bull Pennant',group:PatternGroup.continuation,shape:PatternShape.pennant,classification:'استمراري',direction:'صاعد',description:'اندفاع قوي ثم نطاق صغير متضيق قبل الاستمرار.',structure:'سارية + مثلث صغير',confirmation:'كسر الضلع العلوي مع سياق صاعد.',notes:'لا تخلطها مع مثلث كبير متعدد المراحل.'),
  PatternInfo(name:'الراية الهابطة',english:'Bear Pennant',group:PatternGroup.continuation,shape:PatternShape.pennant,classification:'استمراري',direction:'هابط',description:'اندفاع هابط ثم نطاق صغير متضيق قبل الاستمرار.',structure:'سارية + مثلث صغير',confirmation:'كسر الضلع السفلي مع سياق هابط.',notes:'انتظر الخروج ولا تفترض اتجاهه مسبقاً.'),
  PatternInfo(name:'المستطيل الصاعد',english:'Bullish Rectangle',group:PatternGroup.continuation,shape:PatternShape.rectangle,classification:'استمراري',direction:'صاعد',description:'تذبذب أفقي بين دعم ومقاومة أثناء سياق صاعد.',structure:'حد علوي + حد سفلي',confirmation:'اختراق الحد العلوي مع تأكيد.',notes:'قد يفشل ويكسر الحد المقابل.'),
  PatternInfo(name:'المستطيل الهابط',english:'Bearish Rectangle',group:PatternGroup.continuation,shape:PatternShape.rectangle,classification:'استمراري',direction:'هابط',description:'تذبذب أفقي بين دعم ومقاومة أثناء سياق هابط.',structure:'حد علوي + حد سفلي',confirmation:'كسر الحد السفلي مع تأكيد.',notes:'ليس كل نطاق عرضي إشارة اتجاه.'),
  PatternInfo(name:'الكوب والعروة',english:'Cup & Handle',group:PatternGroup.continuation,shape:PatternShape.cupHandle,classification:'استمراري',direction:'صاعد',description:'قاع مستدير يشبه الكوب ثم تصحيح أصغر يمثل العروة.',structure:'كوب + عروة + مقاومة',confirmation:'اختراق المقاومة بعد العروة.',notes:'يحتاج سياقاً زمنياً مناسباً.'),
  PatternInfo(name:'الكوب والعروة المعكوس',english:'Inverse Cup & Handle',group:PatternGroup.continuation,shape:PatternShape.inverseCupHandle,classification:'استمراري',direction:'هابط',description:'قمة مستديرة ثم تصحيح أصغر في سياق هابط.',structure:'كوب مقلوب + عروة + دعم',confirmation:'كسر الدعم بعد العروة.',notes:'إطار تعليمي وليس إشارة آلية.'),
  PatternInfo(name:'المثلث الصاعد',english:'Ascending Triangle',group:PatternGroup.triangles,shape:PatternShape.ascendingTriangle,classification:'استمراري أو انعكاسي',direction:'صاعد غالباً عند الكسر العلوي',description:'مقاومة شبه أفقية مع قيعان تصعد تدريجياً نحوها.',structure:'مقاومة أفقية + قيعان صاعدة',confirmation:'اختراق المقاومة أو فشل الاختراق.',notes:'قد يظهر انعكاسياً بعد هبوط؛ السياق يحكم.'),
  PatternInfo(name:'المثلث الهابط',english:'Descending Triangle',group:PatternGroup.triangles,shape:PatternShape.descendingTriangle,classification:'استمراري أو انعكاسي',direction:'هابط غالباً عند الكسر السفلي',description:'دعم شبه أفقي مع قمم تهبط تدريجياً نحوه.',structure:'دعم أفقي + قمم هابطة',confirmation:'كسر الدعم أو مراقبة فشل الكسر.',notes:'قد يظهر انعكاسياً في نهاية اتجاه صاعد.'),
  PatternInfo(name:'المثلث المتماثل',english:'Symmetrical Triangle',group:PatternGroup.triangles,shape:PatternShape.symmetricalTriangle,classification:'استمراري أو انعكاسي',direction:'حسب الكسر والسياق',description:'خط قمم هابط وخط قيعان صاعد يلتقيان نحو نقطة.',structure:'ضلع علوي هابط + ضلع سفلي صاعد',confirmation:'كسر أحد الضلعين ثم تأكيد.',notes:'لا تفترض الصعود أو الهبوط قبل الكسر.'),
  PatternInfo(name:'الوتد الصاعد',english:'Rising Wedge',group:PatternGroup.context,shape:PatternShape.wedge,classification:'انعكاسي أو استمراري',direction:'هابط غالباً عند الكسر السفلي',description:'ضلعان صاعدان يتقاربان وقد يظهران في الصعود أو كتصحيح.',structure:'خطا اتجاه صاعدان متقاربان',confirmation:'كسر الضلع السفلي ثم تأكيد.',notes:'الوتد لا يعني هبوطاً تلقائياً.'),
  PatternInfo(name:'الوتد الهابط',english:'Falling Wedge',group:PatternGroup.context,shape:PatternShape.wedge,classification:'انعكاسي أو استمراري',direction:'صاعد غالباً عند الكسر العلوي',description:'ضلعان هابطان يتقاربان وقد يظهران بعد هبوط أو كتصحيح.',structure:'خطا اتجاه هابطان متقاربان',confirmation:'اختراق الضلع العلوي ثم تأكيد.',notes:'البنية والسياق أهم من الاسم.'),
  PatternInfo(name:'القناة الصاعدة',english:'Ascending Channel',group:PatternGroup.context,shape:PatternShape.channel,classification:'سياقي / استمراري',direction:'صاعد',description:'حدان متوازيان يصعدان ويحتويان حركة السعر.',structure:'مقاومة مائلة + دعم مائل',confirmation:'راقب تفاعل السعر مع الحدود ثم تأكيد الكسر.',notes:'القناة تصف البنية ولا تضمن استمرارها.'),
  PatternInfo(name:'القناة الهابطة',english:'Descending Channel',group:PatternGroup.context,shape:PatternShape.channel,classification:'سياقي / استمراري',direction:'هابط',description:'حدان متوازيان يهبطان ويحتويان حركة السعر.',structure:'مقاومة هابطة + دعم هابط',confirmation:'راقب الحدود ثم تأكيد الكسر.',notes:'قد تكون القناة تصحيحاً ضمن اتجاه أكبر.'),
  PatternInfo(name:'النطاق المتسع',english:'Broadening Pattern',group:PatternGroup.context,shape:PatternShape.broadening,classification:'سياقي',direction:'حسب الكسر والسياق',description:'قمم أعلى وقيعان أدنى فتتباعد حدود الحركة.',structure:'خط علوي صاعد + خط سفلي هابط',confirmation:'انتظر خروجاً واضحاً وسياقاً متوافقاً.',notes:'التذبذب العالي يتطلب حذراً تعليمياً.'),
  PatternInfo(name:'Pin Bar صاعدة',english:'Bullish Pin Bar',group:PatternGroup.candles,shape:PatternShape.pinBar,classification:'شمعة سعرية',direction:'صاعد',description:'جسم صغير مع ذيل سفلي بارز وقد تعبر عن رفض الأسعار المنخفضة.',structure:'ذيل سفلي طويل + جسم صغير',confirmation:'منطقة دعم أو سياق مناسب ثم تأكيد.',notes:'لا تعتمد عليها وحدها في منتصف نطاق عشوائي.'),
  PatternInfo(name:'Pin Bar هابطة',english:'Bearish Pin Bar',group:PatternGroup.candles,shape:PatternShape.pinBar,classification:'شمعة سعرية',direction:'هابط',description:'جسم صغير مع ذيل علوي بارز وقد تعبر عن رفض الأسعار المرتفعة.',structure:'ذيل علوي طويل + جسم صغير',confirmation:'منطقة مقاومة أو سياق مناسب ثم تأكيد.',notes:'السياق أهم من الاسم.'),
  PatternInfo(name:'الابتلاع الصاعد',english:'Bullish Engulfing',group:PatternGroup.candles,shape:PatternShape.engulfing,classification:'شمعة سعرية',direction:'صاعد',description:'شمعة صاعدة كبيرة تغطي جسم الشمعة الهابطة السابقة في الشكل الشائع.',structure:'هابطة صغيرة + صاعدة أكبر',confirmation:'وجودها عند دعم أو بعد هبوط ثم متابعة الحركة.',notes:'الحجوم النسبية تختلف بين الأسواق والفريمات.'),
  PatternInfo(name:'الابتلاع الهابط',english:'Bearish Engulfing',group:PatternGroup.candles,shape:PatternShape.engulfing,classification:'شمعة سعرية',direction:'هابط',description:'شمعة هابطة كبيرة تغطي جسم الشمعة الصاعدة السابقة في الشكل الشائع.',structure:'صاعدة صغيرة + هابطة أكبر',confirmation:'وجودها عند مقاومة أو بعد صعود ثم متابعة الحركة.',notes:'لا يعني الانعكاس حتماً دون سياق.'),
  PatternInfo(name:'دوجي',english:'Doji',group:PatternGroup.candles,shape:PatternShape.doji,classification:'محايد',direction:'محايد',description:'افتتاح وإغلاق متقاربان مع ظلال قد تكون واضحة ويعكس تردداً نسبياً.',structure:'جسم صغير جداً',confirmation:'لا يستخدم وحده؛ راقب المنطقة والشمعة التالية.',notes:'دوجي ليس شراءً أو بيعاً تلقائياً.'),
  PatternInfo(name:'نجمة الصباح',english:'Morning Star',group:PatternGroup.candles,shape:PatternShape.star,classification:'انعكاسي',direction:'صاعد',description:'تكوين من ثلاث شموع يرتبط غالباً بانتقال من هبوط إلى صعود.',structure:'هبوط + شمعة وسطية صغيرة + صاعدة قوية',confirmation:'متابعة القوة الصاعدة داخل منطقة مناسبة.',notes:'الفجوات ليست شرطاً عملياً في كل سوق.'),
  PatternInfo(name:'نجمة المساء',english:'Evening Star',group:PatternGroup.candles,shape:PatternShape.star,classification:'انعكاسي',direction:'هابط',description:'تكوين من ثلاث شموع يرتبط غالباً بانتقال من صعود إلى هبوط.',structure:'صعود + شمعة وسطية صغيرة + هابطة قوية',confirmation:'متابعة الضعف الهابط داخل منطقة مناسبة.',notes:'السياق ومستوى السعر أهم من الاسم وحده.'),
];

class PatternLibraryPage extends StatefulWidget {
  const PatternLibraryPage({super.key});
  @override State<PatternLibraryPage> createState()=>_PatternLibraryPageState();
}
class _PatternLibraryPageState extends State<PatternLibraryPage>{
  int filter=0;
  List<PatternInfo> get visible{
    if(filter==0)return patternLibrary;
    const groups=[PatternGroup.reversal,PatternGroup.continuation,PatternGroup.triangles,PatternGroup.candles,PatternGroup.context];
    return patternLibrary.where((p)=>p.group==groups[filter-1]).toList();
  }
  String groupName(PatternGroup g){switch(g){case PatternGroup.reversal:return'انعكاسي';case PatternGroup.continuation:return'استمراري';case PatternGroup.triangles:return'مثلثات';case PatternGroup.candles:return'شموع';case PatternGroup.context:return'قنوات وأوتاد';}}
  @override Widget build(BuildContext context){
    const filters=['الكل','الانعكاسية','الاستمرارية','المثلثات','الشموع','القنوات والأوتاد'];
    return Scaffold(appBar:AppBar(title:const Text('جميع النماذج'),actions:[Center(child:Padding(padding:const EdgeInsetsDirectional.only(end:14),child:Text('\$'+'{visible.length}',style:const TextStyle(color:Colors.cyanAccent,fontWeight:FontWeight.w900))))]),body:ListView(padding:const EdgeInsets.fromLTRB(14,8,14,30),children:[
      Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:const Color(0xFF0D1722),borderRadius:BorderRadius.circular(20),border:Border.all(color:Colors.cyanAccent.withValues(alpha:.55))),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('مكتبة النماذج الرئيسية',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900)),SizedBox(height:6),Text('لكل نموذج: الاسم، الشكل على الشارت، التصنيف، الاتجاه الصاعد/الهابط/المحايد، الشرح، البنية، والتأكيد.',style:TextStyle(color:Colors.white70,height:1.55))])),
      const SizedBox(height:12),
      SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:[for(int i=0;i<filters.length;i++)Padding(padding:const EdgeInsetsDirectional.only(end:8),child:ChoiceChip(label:Text(filters[i]),selected:filter==i,onSelected:(_)=>setState(()=>filter=i)))])),
      const SizedBox(height:14),
      for(int i=0;i<visible.length;i++)PatternCard(info:visible[i],index:i+1,groupName:groupName(visible[i].group)),
    ]));
  }
}

class PatternCard extends StatelessWidget{
  final PatternInfo info;final int index;final String groupName;
  const PatternCard({super.key,required this.info,required this.index,required this.groupName});
  Color get accent{switch(info.group){case PatternGroup.reversal:return Colors.redAccent;case PatternGroup.continuation:return Colors.greenAccent;case PatternGroup.triangles:return Colors.amber;case PatternGroup.candles:return Colors.cyanAccent;case PatternGroup.context:return Colors.deepPurpleAccent;}}
  @override Widget build(BuildContext context){
    final bull=info.direction.contains('صاعد'),bear=info.direction.contains('هابط');
    final dirColor=bull?Colors.greenAccent:bear?Colors.redAccent:Colors.white70;
    return Card(margin:const EdgeInsets.only(bottom:14),clipBehavior:Clip.antiAlias,child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
      Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Container(width:38,height:38,alignment:Alignment.center,decoration:BoxDecoration(color:accent.withValues(alpha:.12),borderRadius:BorderRadius.circular(12),border:Border.all(color:accent.withValues(alpha:.55))),child:Text('$index',style:TextStyle(color:accent,fontWeight:FontWeight.w900))),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(info.name,style:const TextStyle(fontSize:19,fontWeight:FontWeight.w900)),const SizedBox(height:2),Text(info.english,style:TextStyle(color:accent,fontWeight:FontWeight.w700))]))]),
      const SizedBox(height:10),SizedBox(height:205,width:double.infinity,child:PatternChart(shape:info.shape,direction:info.direction)),const SizedBox(height:9),
      Wrap(spacing:7,runSpacing:7,children:[BadgeP(text:groupName,color:accent),BadgeP(text:info.classification,color:accent),BadgeP(text:info.direction,color:dirColor)]),
      const SizedBox(height:12),PatternLine(title:'ما هو؟',text:info.description,icon:Icons.info_outline,color:accent),PatternLine(title:'الشكل والبنية',text:info.structure,icon:Icons.account_tree_outlined,color:Colors.white70),PatternLine(title:'التأكيد',text:info.confirmation,icon:Icons.verified_outlined,color:Colors.amber),PatternLine(title:'ملاحظة',text:info.notes,icon:Icons.lightbulb_outline,color:Colors.white54),
    ])));
  }
}
class BadgeP extends StatelessWidget{final String text;final Color color;const BadgeP({super.key,required this.text,required this.color});@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:6),decoration:BoxDecoration(color:color.withValues(alpha:.09),borderRadius:BorderRadius.circular(14),border:Border.all(color:color.withValues(alpha:.6))),child:Text(text,style:TextStyle(color:color,fontSize:12,fontWeight:FontWeight.w800)));}
class PatternLine extends StatelessWidget{final String title,text;final IconData icon;final Color color;const PatternLine({super.key,required this.title,required this.text,required this.icon,required this.color});@override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.only(bottom:9),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(icon,color:color,size:19),const SizedBox(width:7),Expanded(child:RichText(text:TextSpan(style:const TextStyle(color:Colors.white70,height:1.45),children:[TextSpan(text:'$title: ',style:TextStyle(color:color,fontWeight:FontWeight.w900)),TextSpan(text:text)])))]));}

class PatternChart extends StatelessWidget{
  final PatternShape shape;final String direction;
  const PatternChart({super.key,required this.shape,required this.direction});
  @override Widget build(BuildContext context)=>Card(margin:EdgeInsets.zero,color:const Color(0xFF08121C),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16),side:BorderSide(color:Colors.white.withValues(alpha:.08))),child:CustomPaint(painter:PatternChartPainter(shape,direction),child:const SizedBox.expand()));
}
class PatternChartPainter extends CustomPainter{
  final PatternShape shape;final String direction;PatternChartPainter(this.shape,this.direction);
  void path(Canvas c,Paint p,List<Offset> pts){final q=Path()..moveTo(pts.first.dx,pts.first.dy);for(final x in pts.skip(1)){q.lineTo(x.dx,x.dy);}c.drawPath(q,p);}
  void base(Canvas c,Size s){c.drawRRect(RRect.fromRectAndRadius(Offset.zero&s,const Radius.circular(16)),Paint()..color=const Color(0xFF08121C));final g=Paint()..color=Colors.white.withValues(alpha:.045)..strokeWidth=1;for(int i=1;i<5;i++)c.drawLine(Offset(0,s.height*i/5),Offset(s.width,s.height*i/5),g);for(int i=1;i<7;i++)c.drawLine(Offset(s.width*i/7,0),Offset(s.width*i/7,s.height),g);}
  void candles(Canvas c,Size s,List<double> ys){final body=Paint();final wick=Paint()..strokeWidth=1.6;final step=(s.width-36)/(ys.length+1);for(int i=0;i<ys.length;i++){final x=18+step*(i+1),y=ys[i];final col=i.isEven?Colors.greenAccent:Colors.redAccent;wick.color=col;body.color=col;c.drawLine(Offset(x,y-12),Offset(x,y+12),wick);c.drawRect(Rect.fromCenter(center:Offset(x,y),width:8,height:15),body);}}
  void level(Canvas c,Size s,Paint p,double y){c.drawLine(Offset(16,y),Offset(s.width-16,y),p);}
  @override void paint(Canvas c,Size s){base(c,s);final w=s.width;final p=Paint()..style=PaintingStyle.stroke..strokeWidth=3..strokeCap=StrokeCap.round;
    switch(shape){
      case PatternShape.doubleTop:p.color=Colors.redAccent;path(c,p,[Offset(15,160),Offset(w*.25,70),Offset(w*.42,145),Offset(w*.60,72),Offset(w*.78,150),Offset(w-15,165)]);p.color=Colors.amber;level(c,s,p,145);break;
      case PatternShape.doubleBottom:p.color=Colors.greenAccent;path(c,p,[Offset(15,55),Offset(w*.25,145),Offset(w*.42,72),Offset(w*.60,146),Offset(w*.78,70),Offset(w-15,55)]);p.color=Colors.amber;level(c,s,p,72);break;
      case PatternShape.tripleTop:p.color=Colors.redAccent;path(c,p,[Offset(15,155),Offset(w*.17,68),Offset(w*.30,145),Offset(w*.43,68),Offset(w*.56,145),Offset(w*.69,70),Offset(w-15,155)]);p.color=Colors.amber;level(c,s,p,145);break;
      case PatternShape.tripleBottom:p.color=Colors.greenAccent;path(c,p,[Offset(15,58),Offset(w*.17,150),Offset(w*.30,70),Offset(w*.43,150),Offset(w*.56,70),Offset(w*.69,150),Offset(w-15,58)]);p.color=Colors.amber;level(c,s,p,70);break;
      case PatternShape.headShoulders:p.color=Colors.redAccent;path(c,p,[Offset(15,150),Offset(w*.18,92),Offset(w*.30,140),Offset(w*.50,48),Offset(w*.70,140),Offset(w*.82,92),Offset(w-15,150)]);p.color=Colors.amber;level(c,s,p,140);break;
      case PatternShape.inverseHeadShoulders:p.color=Colors.greenAccent;path(c,p,[Offset(15,58),Offset(w*.18,116),Offset(w*.30,68),Offset(w*.50,162),Offset(w*.70,68),Offset(w*.82,116),Offset(w-15,58)]);p.color=Colors.amber;level(c,s,p,68);break;
      case PatternShape.roundingTop:p.color=Colors.redAccent;path(c,p,[Offset(15,65),Offset(w*.20,58),Offset(w*.36,80),Offset(w*.50,118),Offset(w*.64,150),Offset(w*.80,166),Offset(w-15,158)]);break;
      case PatternShape.roundingBottom:p.color=Colors.greenAccent;path(c,p,[Offset(15,158),Offset(w*.20,166),Offset(w*.36,145),Offset(w*.50,110),Offset(w*.64,75),Offset(w*.80,58),Offset(w-15,68)]);break;
      case PatternShape.flag:{final down=direction.contains('هابط');p.color=down?Colors.redAccent:Colors.greenAccent;path(c,p,down?[Offset(15,48),Offset(w*.28,102),Offset(w*.50,158),Offset(w*.72,132),Offset(w-15,145)]:[Offset(15,166),Offset(w*.28,108),Offset(w*.50,52),Offset(w*.72,80),Offset(w-15,65)]);p.color=Colors.amber;path(c,p,down?[Offset(w*.32,88),Offset(w*.86,125)]:[Offset(w*.32,72),Offset(w*.86,105)]);path(c,p,down?[Offset(w*.32,132),Offset(w*.86,160)]:[Offset(w*.32,112),Offset(w*.86,145)]);break;}
      case PatternShape.pennant:{final down=direction.contains('هابط');p.color=down?Colors.redAccent:Colors.greenAccent;path(c,p,down?[Offset(15,48),Offset(w*.28,95),Offset(w*.47,112),Offset(w*.66,102),Offset(w-15,155)]:[Offset(15,162),Offset(w*.28,115),Offset(w*.47,95),Offset(w*.66,106),Offset(w-15,50)]);p.color=Colors.amber;path(c,p,[Offset(w*.28,72),Offset(w*.48,105),Offset(w*.70,122)]);path(c,p,[Offset(w*.28,145),Offset(w*.48,105),Offset(w*.70,94)]);break;}
      case PatternShape.ascendingTriangle:p.color=Colors.amber;level(c,s,p,55);p.color=Colors.greenAccent;path(c,p,[Offset(15,165),Offset(w*.30,138),Offset(w*.52,110),Offset(w*.74,82),Offset(w-15,58)]);break;
      case PatternShape.descendingTriangle:p.color=Colors.amber;level(c,s,p,160);p.color=Colors.redAccent;path(c,p,[Offset(15,52),Offset(w*.30,80),Offset(w*.52,110),Offset(w*.74,138),Offset(w-15,160)]);break;
      case PatternShape.symmetricalTriangle:p.color=Colors.redAccent;path(c,p,[Offset(15,48),Offset(w*.50,105),Offset(w-15,160)]);p.color=Colors.greenAccent;path(c,p,[Offset(15,165),Offset(w*.50,105),Offset(w-15,50)]);break;
      case PatternShape.rectangle:p.color=Colors.amber;c.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(25,50,w-50,110),const Radius.circular(8)),p);candles(c,s,[130,75,135,70,125,82,132,76]);break;
      case PatternShape.cupHandle:p.color=Colors.greenAccent;path(c,p,[Offset(15,65),Offset(w*.20,68),Offset(w*.34,105),Offset(w*.50,158),Offset(w*.66,105),Offset(w*.79,66),Offset(w*.88,96),Offset(w-15,82)]);p.color=Colors.amber;level(c,s,p,65);break;
      case PatternShape.inverseCupHandle:p.color=Colors.redAccent;path(c,p,[Offset(15,158),Offset(w*.20,153),Offset(w*.34,110),Offset(w*.50,58),Offset(w*.66,110),Offset(w*.79,154),Offset(w*.88,124),Offset(w-15,140)]);p.color=Colors.amber;level(c,s,p,153);break;
      case PatternShape.wedge:{final rising=direction.contains('صاعد');p.color=rising?Colors.redAccent:Colors.greenAccent;path(c,p,rising?[Offset(15,158),Offset(w-15,55)]:[Offset(15,55),Offset(w-15,158)]);path(c,p,rising?[Offset(15,112),Offset(w-15,92)]:[Offset(15,92),Offset(w-15,112)]);break;}
      case PatternShape.channel:{final down=direction.contains('هابط');p.color=down?Colors.redAccent:Colors.greenAccent;final y1=down?55.0:150.0,y2=down?112.0:55.0;path(c,p,[Offset(15,y1),Offset(w-15,y2)]);path(c,p,[Offset(15,y1+70),Offset(w-15,y2+70)]);break;}
      case PatternShape.broadening:p.color=Colors.amber;path(c,p,[Offset(15,72),Offset(w-15,35)]);path(c,p,[Offset(15,145),Offset(w-15,180)]);p.color=Colors.cyanAccent;path(c,p,[Offset(25,112),Offset(w*.28,58),Offset(w*.48,138),Offset(w*.68,48),Offset(w-20,165)]);break;
      case PatternShape.pinBar:{final bull=direction.contains('صاعد');candles(c,s,bull?[138,120,108,92,100]:[70,86,105,122,135]);final x=w*.60;p.color=bull?Colors.greenAccent:Colors.redAccent;p.strokeWidth=4;c.drawLine(Offset(x,bull?100:25),Offset(x,bull?190:112),p);c.drawRect(Rect.fromCenter(center:Offset(x,bull?105:100),width:18,height:25),Paint()..color=p.color);break;}
      case PatternShape.engulfing:{final bull=direction.contains('صاعد');candles(c,s,bull?[138,125,116,100,86]:[70,82,95,110,126]);final x1=w*.48,x2=w*.61;c.drawRect(Rect.fromCenter(center:Offset(x1,bull?118:92),width:14,height:22),Paint()..color=(bull?Colors.redAccent:Colors.greenAccent));c.drawRect(Rect.fromCenter(center:Offset(x2,bull?96:114),width:25,height:58),Paint()..color=(bull?Colors.greenAccent:Colors.redAccent));break;}
      case PatternShape.doji:candles(c,s,[120,112,105,96,105,112]);{final x=w*.56;p.color=Colors.cyanAccent;c.drawLine(Offset(x,42),Offset(x,158),p);c.drawLine(Offset(x-11,100),Offset(x+11,100),p);break;}
      case PatternShape.star:{final morning=direction.contains('صاعد');candles(c,s,morning?[95,108,100,86,70]:[95,82,92,112,130]);final x=w*.52;c.drawRect(Rect.fromCenter(center:Offset(x,morning?105:92),width:11,height:16),Paint()..color=Colors.amber);p.color=morning?Colors.greenAccent:Colors.redAccent;c.drawLine(Offset(w*.64,morning?110:78),Offset(w*.86,morning?62:140),p);break;}
    }
  }
  @override bool shouldRepaint(covariant PatternChartPainter oldDelegate)=>oldDelegate.shape!=shape||oldDelegate.direction!=direction;
}
